# SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut
# SPDX-License-Identifier: Apache-2.0

"""The Tiny Tapeout submission tree must not drift from hw/rtl.

tt/ is generated by scripts/gen_tt_submission.py: the RTL is copied out
of hw/rtl byte for byte, and the datasheet's register table is rendered
from sw/golden/regmap_gen.py. That only buys anything if the copy is
enforced, so this module checks the tree three independent ways:

  * every file listed in tt/MANIFEST.sha256 hashes to what the manifest
    says, and the manifest covers every generated file;
  * every RTL file in tt/src is byte-identical to hw/rtl, and nothing
    under tt/src is anything else;
  * re-running the generator in memory produces exactly the tree on
    disk (this is what catches a register-map edit, a pinout edit or a
    hand edit anywhere under tt/).

Plus a set of assertions about the submission itself, made against the
files on disk rather than against the generator, so that a bug in the
generator cannot make them vacuous: the tile shape, the top module, the
schema version, the fact that every declared source file exists, and
the pin contract -- names AND the wires under them, read out of the
wrapper's RTL rather than out of its header comment.

If this fails after an intentional change, the fix is:

    python3 scripts/gen_tt_submission.py

Nothing under tt/ is ever edited by hand.
"""

import hashlib
import importlib.util
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TT = ROOT / "tt"
GENERATOR = ROOT / "scripts" / "gen_tt_submission.py"

# The pilot's Tiny Tapeout pin budget, fixed by the shuttle.
PIN_GROUPS = {"ui": 8, "uo": 8, "uio": 8}


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_tt_submission", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules["gen_tt_submission"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def gen():
    assert GENERATOR.is_file(), f"generator not found at {GENERATOR}"
    return _load_generator()


@pytest.fixture(scope="module")
def built(gen):
    """The tree as the generator would write it, {relpath: bytes}."""
    return gen.build()


@pytest.fixture(scope="module")
def info_yaml():
    yaml = pytest.importorskip("yaml")
    path = TT / "info.yaml"
    assert path.is_file(), "tt/info.yaml is missing; run the generator"
    return yaml.safe_load(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------
# 1. the tree exists and matches its own manifest
# ---------------------------------------------------------------------
def test_submission_tree_exists():
    assert TT.is_dir(), (
        "tt/ does not exist. Run: python3 scripts/gen_tt_submission.py"
    )


def test_manifest_hashes_match_the_files():
    manifest = TT / "MANIFEST.sha256"
    assert manifest.is_file(), "tt/MANIFEST.sha256 is missing"
    bad = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        digest, rel = line.split("  ", 1)
        target = TT / rel
        if not target.is_file():
            bad.append(f"{rel}: listed in the manifest but not on disk")
            continue
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        if actual != digest:
            bad.append(f"{rel}: manifest {digest[:12]}, file {actual[:12]}")
    assert not bad, "tt/MANIFEST.sha256 disagrees with the tree:\n  " + "\n  ".join(bad)


def test_manifest_covers_every_generated_file(gen):
    manifest = TT / "MANIFEST.sha256"
    listed = {
        line.split("  ", 1)[1]
        for line in manifest.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }
    missing = []
    for path in sorted(TT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(TT).as_posix()
        if rel == "MANIFEST.sha256" or not gen.is_generated(rel):
            continue
        if rel not in listed:
            missing.append(rel)
    assert not missing, (
        "files under tt/ that the manifest does not cover:\n  "
        + "\n  ".join(missing)
    )


# ---------------------------------------------------------------------
# 2. the RTL really is a copy
# ---------------------------------------------------------------------
def test_rtl_sources_are_byte_identical_to_hw_rtl(gen):
    mismatched = []
    for name in gen.RTL_SOURCES + gen.RTL_INCLUDES:
        source = ROOT / "hw" / "rtl" / name
        copy = TT / "src" / name
        assert source.is_file(), f"hw/rtl/{name} is missing"
        assert copy.is_file(), f"tt/src/{name} is missing; run the generator"
        if source.read_bytes() != copy.read_bytes():
            mismatched.append(name)
    assert not mismatched, (
        "tt/src has drifted from hw/rtl for: " + ", ".join(mismatched)
        + "\nRun: python3 scripts/gen_tt_submission.py"
    )


def test_every_source_under_src_is_a_copy(gen):
    """Nothing under tt/src is generated: every .v and .vh comes from hw/rtl.

    The submission used to carry one generated file, a name adapter that
    wrapped hw/rtl/tt_um_pilot.v in a shuttle-unique module name. The
    wrapper now carries that name itself, so the adapter is gone and this
    test holds the stronger property: what is hardened is exactly what is
    simulated in the source repository, with no extra hierarchy level.
    """
    expected = set(gen.RTL_SOURCES) | set(gen.RTL_INCLUDES)
    found = {
        p.name for p in (TT / "src").iterdir()
        if p.suffix in (".v", ".vh")
    }
    assert found == expected, (
        f"unexpected sources under tt/src: {sorted(found - expected)}; "
        f"missing: {sorted(expected - found)}"
    )
    assert not hasattr(gen, "ADAPTER_NAME"), (
        "the generator grew a name adapter again; the top module is "
        "supposed to be namespaced in hw/rtl itself"
    )


# ---------------------------------------------------------------------
# 3. regenerating produces exactly what is on disk
# ---------------------------------------------------------------------
def test_tree_matches_the_generator(gen, built):
    problems = gen.check(built, TT)
    assert not problems, (
        "the submission tree is out of date:\n  " + "\n  ".join(problems)
        + "\nRun: python3 scripts/gen_tt_submission.py"
    )


# ---------------------------------------------------------------------
# 4. assertions about the submission, read off the tree on disk
# ---------------------------------------------------------------------
def test_tile_shape_is_the_documented_decision(info_yaml):
    # 4x2 until 2026-08-30, when the re-harden measured it over the 70 %
    # planning criterion (docs/22: 71.489 % and 5,527 um2 short). Both
    # twelve-tile shapes were then hardened and compared in docs/23, and
    # 6x2 won on routing, timing, antenna and clock skew -- not on area,
    # since both clear the criterion with room to spare. 6x2 is also the
    # only one of the two confirmed purchasable on TTIHP26b.
    assert info_yaml["project"]["tiles"] == "6x2", (
        "docs/23-tile-shape-decision.md decides 6x2 = 12 tiles; info.yaml "
        f"says {info_yaml['project']['tiles']!r}"
    )


def test_yaml_schema_version(info_yaml):
    assert info_yaml["yaml_version"] == 6, (
        "tt-support-tools project_info.py pins YAML_VERSION = 6"
    )


def test_top_module_is_namespaced(info_yaml):
    top = info_yaml["project"]["top_module"]
    assert top.startswith("tt_um_"), "the top module must start with tt_um_"
    assert top != "tt_um_pilot", (
        "the shuttle asserts that macro names are unique across every "
        "project; the submission top level must be namespaced"
    )


def test_declared_source_files_exist_and_define_the_top(info_yaml):
    sources = info_yaml["project"]["source_files"]
    assert sources, "info.yaml declares no source files"
    top = info_yaml["project"]["top_module"]
    defining = []
    for name in sources:
        path = TT / "src" / name
        assert path.is_file(), f"info.yaml lists {name}, which is not in tt/src"
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("module ") and stripped[7:].lstrip().startswith(top):
                defining.append(name)
                break
    assert len(defining) == 1, (
        f"tt-support-tools requires the top module {top!r} to be defined in "
        f"exactly one source file; found it in {defining}"
    )


def test_every_pin_is_declared(info_yaml):
    pinout = info_yaml["pinout"]
    for group, count in PIN_GROUPS.items():
        for i in range(count):
            key = f"{group}[{i}]"
            assert key in pinout, f"info.yaml pinout is missing {key}"
    extra = set(pinout) - {
        f"{g}[{i}]" for g, n in PIN_GROUPS.items() for i in range(n)
    }
    assert not extra, f"info.yaml pinout has unexpected keys: {sorted(extra)}"


def _wrapper_path(info_yaml):
    """hw/rtl/<top>.v, named after the module as every file in hw/rtl is."""
    top = info_yaml["project"]["top_module"]
    path = ROOT / "hw" / "rtl" / f"{top}.v"
    assert path.is_file(), (
        f"info.yaml declares top module {top!r}, but hw/rtl/{top}.v does not "
        f"exist; hw/rtl names every file after the module it defines"
    )
    return path


def _wrapper_parts(info_yaml):
    """(header comment block, RTL body) of the Tiny Tapeout wrapper."""
    text = _wrapper_path(info_yaml).read_text(encoding="utf-8")
    cut = text.index("\nmodule ")
    return text[:cut], text[cut:]


def test_pinout_matches_the_wrapper_header(info_yaml):
    """The names in info.yaml must be the names in the wrapper's header.

    The wrapper's header table is the pin contract that docs/15 section 2
    and the datasheet both reproduce. This is the check that stops the
    three from drifting apart silently. All 24 pins are covered: the
    dedicated inputs and outputs one per line, and the bidirectionals as
    the two nibble ranges the header declares them in.
    """
    pinout = info_yaml["pinout"]
    header, _ = _wrapper_parts(info_yaml)
    for i in range(8):
        for group, port in (("ui", "ui_in"), ("uo", "uo_out")):
            name = pinout[f"{group}[{i}]"]
            if not name:
                continue
            needle = f"{port}[{i}] {name}"
            assert needle in header, (
                f"info.yaml calls {group}[{i}] {name!r}, which does not appear "
                f"as {needle!r} in the wrapper header"
            )
    # The bidirectionals are declared as nibbles, so the header carries
    # the base name once and info.yaml indexes it eight times.
    for i in range(8):
        name = pinout[f"uio[{i}]"]
        assert name, f"uio[{i}] has no name in info.yaml"
        m = re.fullmatch(r"([A-Z0-9_]+)\[(\d+)\]", name)
        assert m, (
            f"uio[{i}] is {name!r}; a bidirectional pin must be named "
            f"BASE[index] so the nibble it belongs to is unambiguous"
        )
        assert m.group(1) in header, (
            f"info.yaml calls uio[{i}] {name!r}, but {m.group(1)!r} does not "
            f"appear in the wrapper header"
        )


def test_wrapper_wiring_matches_the_pinout(info_yaml):
    """The names are one thing; this checks the wires under them.

    A pin table agrees with a header comment as easily when the header is
    wrong as when it is right. Everything below is read out of the RTL:
    the port connections of the pilot instance, the uo_out concatenation
    and the uio direction constant. Two pins swapped in the design, or a
    pin table that describes a design nobody built, fails here.
    """
    pinout = info_yaml["pinout"]
    _, body = _wrapper_parts(info_yaml)

    # Dedicated inputs: each named ui pin drives the pilot port of the
    # same name, and the unnamed one drives nothing.
    for i in range(8):
        name = pinout[f"ui[{i}]"]
        conn = re.search(rf"\.(\w+)\s*\(\s*ui_in\[{i}\]\s*\)", body)
        if not name:
            assert conn is None, (
                f"ui[{i}] is declared reserved but the wrapper wires it to "
                f".{conn.group(1)}()"
            )
            continue
        assert conn, f"ui[{i}] is {name!r} but nothing in the wrapper reads it"
        assert conn.group(1) == name.lower(), (
            f"ui[{i}] is {name!r} but the wrapper wires it to "
            f".{conn.group(1)}(), not .{name.lower()}()"
        )

    # Dedicated outputs: uo_out is one concatenation, MSB first.
    m = re.search(r"assign\s+uo_out\s*=\s*\{([^}]*)\}\s*;", body)
    assert m, "the wrapper must drive uo_out from a single concatenation"
    fields = [f.strip() for f in m.group(1).split(",")]
    assert len(fields) == 8, f"uo_out concatenation has {len(fields)} fields"
    for i in range(8):
        name = pinout[f"uo[{i}]"]
        wire = fields[7 - i]              # field 0 is the most significant
        assert wire.startswith(name.lower()), (
            f"uo[{i}] is {name!r} but bit {i} of uo_out is driven by "
            f"{wire!r}"
        )
        assert re.search(rf"\.\w+\s*\(\s*{re.escape(wire)}\s*\)", body), (
            f"uo_out bit {i} is driven by {wire!r}, which the wrapper never "
            f"connects to the design"
        )

    # Bidirectionals: the direction word, and the two nibbles under it.
    m = re.search(r"assign\s+uio_oe\s*=\s*8'b([01_]+)\s*;", body)
    assert m, (
        "the wrapper must fix uio_oe to an 8-bit constant; a runtime "
        "direction would break the pin contract in the datasheet"
    )
    oe = int(m.group(1).replace("_", ""), 2)
    claimed = re.search(r"`uio_oe` is fixed at `0x([0-9A-F]{2})`",
                        (TT / "docs" / "info.md").read_text(encoding="utf-8"))
    assert claimed, "the datasheet must state the uio direction word"
    assert oe == int(claimed.group(1), 16), (
        f"the wrapper sets uio_oe = 0x{oe:02X}, the datasheet says "
        f"0x{int(claimed.group(1), 16):02X}"
    )

    m = re.search(r"\.(\w+)\s*\(\s*uio_in\[(\d+):(\d+)\]\s*\)", body)
    assert m, "the wrapper must take its bidirectional inputs from uio_in"
    in_name, in_hi, in_lo = m.group(1), int(m.group(2)), int(m.group(3))
    m = re.search(r"assign\s+uio_out\s*=\s*\{\s*(\w+)\s*,\s*(\d+)'b[01_]+\s*\}\s*;",
                  body)
    assert m, (
        "the wrapper must drive uio_out from one signal padded with "
        "constants; anything else needs this test rewritten deliberately"
    )
    out_name, out_lo = m.group(1), int(m.group(2))

    for i in range(8):
        name = pinout[f"uio[{i}]"]
        base, index = re.fullmatch(r"([A-Z0-9_]+)\[(\d+)\]", name).groups()
        is_output = bool((oe >> i) & 1)
        if is_output:
            assert i >= out_lo, f"uio[{i}] is an output but carries no signal"
            expect_base, expect_index = out_name.upper(), i - out_lo
        else:
            assert in_lo <= i <= in_hi, (
                f"uio[{i}] is an input but the wrapper reads no such bit"
            )
            expect_base, expect_index = in_name.upper(), i - in_lo
        assert (base, int(index)) == (expect_base, expect_index), (
            f"uio[{i}] is {name!r}, but the wrapper wires that bit to "
            f"{expect_base}[{expect_index}]"
        )


def test_datasheet_has_the_required_sections():
    """tt-support-tools project_checks.py rejects the template placeholders."""
    info_md = (TT / "docs" / "info.md").read_text(encoding="utf-8")
    for heading in ("## How it works", "## How to test", "## External hardware"):
        assert heading in info_md, f"docs/info.md is missing {heading!r}"
    for placeholder in (
        "# How it works\n\nExplain how your project works",
        "# How to test\n\nExplain how to use your project",
    ):
        assert placeholder not in info_md, (
            "docs/info.md still carries a template placeholder, which the "
            "Tiny Tapeout docs check rejects"
        )


def test_register_offsets_in_the_datasheet_match_the_register_map():
    """The datasheet table is rendered from regmap; prove it independently."""
    sys.path.insert(0, str(ROOT / "sw"))
    from golden.regmap_gen import ADDR  # noqa: E402

    info_md = (TT / "docs" / "info.md").read_text(encoding="utf-8")
    wrong = []
    for line in info_md.splitlines():
        if not line.startswith("| 0x"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 2:
            continue
        offset_text, name = cells[0], cells[1]
        if name not in ADDR:
            continue  # a pilot-only register, checked by its own table
        if int(offset_text, 16) != ADDR[name]:
            wrong.append(f"{name}: datasheet {offset_text}, regmap 0x{ADDR[name]:03X}")
    assert not wrong, "docs/info.md disagrees with regmap/regmap.yaml:\n  " + "\n  ".join(wrong)


def test_licence_state_is_declared():
    """The submission must carry the licence the memo was signed for.

    INVERTED 2026-09-09. Until that date this test asserted the opposite
    -- that no `LICENSE` existed and that `LICENSE.PENDING.md` did --
    because publishing design sources with no grant is worse than any of
    the candidate licences and the memo was unsigned. `docs/14` section
    11 is now signed, so the same question ("is this tree publishable?")
    has the same answer for the opposite reason, and the guard is turned
    round rather than deleted. It caught the change it was written for:
    the first regeneration after the signature failed it.
    """
    assert not (TT / "LICENSE.PENDING.md").exists(), (
        "tt/LICENSE.PENDING.md is back; the licence is decided and the "
        "placeholder must not return"
    )
    licence = TT / "LICENSE"
    assert licence.is_file(), (
        "tt/LICENSE is missing. A Tiny Tapeout submission is a public "
        "repository; publishing src/ without it grants nothing"
    )
    text = licence.read_text(encoding="utf-8")
    assert "CERN Open Hardware Licence Version 2 - Weakly Reciprocal" in text, (
        "tt/LICENSE is not CERN-OHL-W-2.0, which is what docs/14 section "
        "6.4 names for hardware sources"
    )
    # The scaffolding keeps the licence it arrived under, and the README
    # has to say so or the split is undeclared.
    assert (TT / "LICENSES" / "Apache-2.0.txt").is_file(), (
        "the upstream template scaffolding is Apache-2.0 as received and "
        "tt/LICENSES/Apache-2.0.txt is where that text lives"
    )
    readme = (TT / "README.md").read_text(encoding="utf-8")
    for token in ("CERN-OHL-W-2.0", "Apache-2.0"):
        assert token in readme, (
            "tt/README.md does not name {}; a two-licence tree with an "
            "undeclared boundary is the thing this test exists to "
            "prevent".format(token)
        )
    # Both texts must be the repository's own copies, not a paraphrase.
    for rel in ("LICENSE", "LICENSES/Apache-2.0.txt"):
        src = {"LICENSE": ROOT / "LICENSES" / "CERN-OHL-W-2.0.txt"}.get(
            rel, ROOT / "LICENSES" / "Apache-2.0.txt")
        assert (TT / rel).read_bytes() == src.read_bytes(), (
            "tt/{} has drifted from {}; the generator reads it so that "
            "there is one copy".format(rel, src.relative_to(ROOT))
        )


def test_the_signed_memo_is_what_released_the_licence():
    """The tree above is only legitimate if the memo actually says so.

    This is the link the mechanics could otherwise lose: a generator can
    be edited to emit a LICENSE without anyone having decided anything.
    """
    memo = (ROOT / "docs" / "14-licensing-decision.md").read_text(
        encoding="utf-8")
    assert "SIGNED 2026-09-09" in memo, (
        "docs/14 section 11 does not record a signature, so nothing "
        "authorises tt/LICENSE"
    )
    for row in ("CERN-OHL-W-2.0", "Apache-2.0", "CC-BY-4.0"):
        assert row in memo, "docs/14 no longer names {}".format(row)
