#!/usr/bin/env python3
"""Derive the ihp-sg13g2 corner-experiment configs from the submission config.

The IHP re-harden of docs/20 section 2 runs the *submission's own*
config, `tt/src/config_merged.json`, exactly as docs/15 section 5.3 did.
The PNR_CORNERS experiment of docs/20 section 4 must not silently change
anything else, and `tt/src/` is generated by
`scripts/gen_tt_submission.py` and is not this workstream's to write
into. So the experiment config is derived here instead, mechanically,
with two rebasings and one added key:

  * `VERILOG_FILES` is rebased from `tt/src/*.v` to `hw/rtl/*.v`. Those
    are copies, not different sources -- `git hash-object` gives the
    same blob for all seven files -- and reading `hw/rtl` directly means
    the run cannot harden a stale generated copy. `hw/openlane/pilot_sky130`
    already reads `hw/rtl` for the same reason.
  * `FP_DEF_TEMPLATE` is rebased for the extra directory level. It still
    resolves to the same pin-frame DEF inside the gitignored
    `tt/tt/` clone of tt-support-tools.
  * `VERILOG_INCLUDE_DIRS` is added, because `npu_regs.vh` sits beside
    the sources and `tt/src` was its own include directory implicitly.

Everything else is copied through. `--check` re-derives and diffs
against what is on disk, so a drifted config is an error rather than a
surprise in a run directory.

Usage:
    ./mkconfig.py            # write config.json and the three variants
    ./mkconfig.py --check
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SRC = os.path.join(REPO, "tt", "src", "config_merged.json")

# The three ihp-sg13g2 STA corners, as LibreLane resolves them (see any
# runs/*/resolved.json). Note there are three, not sky130's nine: the
# IHP PDK ships one OpenRCX ruleset (nom_*) where sky130 ships three.
PNR_CORNERS = ["nom_typ_1p20V_25C", "nom_slow_1p08V_125C"]

# docs/23: the twelve-tile shape decision. Both entries are twelve tiles
# at the same shuttle price; they differ in aspect ratio and, because the
# tile grid is not a constant-area grid, in die area. DIE_AREA is copied
# verbatim from tt/tt/tech/ihp-sg13g2/tile_sizes.yaml rather than
# recomputed, and the pin-frame DEF is the matching one from the same
# clone, so a shape variant cannot drift from the tile definition
# tt-support-tools would use.
SHAPES = {
    "3x4": ("0 0 636.96 710.64", "tt_block_3x4_pgvdd.def"),
    "6x2": ("0 0 1289.28 313.74", "tt_block_6x2_pgvdd.def"),
}


def derive():
    pairs = json.load(open(SRC), object_pairs_hook=list)
    out = []
    for k, v in pairs:
        if k == "VERILOG_FILES":
            v = ["dir::../../rtl/" + os.path.basename(x.split("::", 1)[1]) for x in v]
        elif k == "FP_DEF_TEMPLATE":
            # Rebase the path, keep the FILE. Hard-coding the 4x2 DEF here
            # was safe only while the submission was 4x2; docs/23 moved it
            # to 6x2 and a hard-coded name would have silently hardened
            # the baseline at a tile shape the submission no longer uses.
            v = "dir::../../../tt/tt/tech/ihp-sg13g2/def/" + os.path.basename(v)
        out.append((k, v))
    out.append(("VERILOG_INCLUDE_DIRS", ["dir::../../rtl"]))
    out.append(
        (
            "//derived",
            "GENERATED by mkconfig.py from tt/src/config_merged.json. "
            "Do not hand-edit; re-run the script.",
        )
    )
    base = list(out)
    variant = list(out) + [
        ("PNR_CORNERS", PNR_CORNERS),
        (
            "//variant",
            "docs/20 section 5: the slow corner inside the PnR optimization "
            "loop rather than only inside the final sign-off STA. "
            "nom_typ_1p20V_25C is DEFAULT_CORNER and is kept so the baseline "
            "behaviour is a subset of this one.",
        ),
    ]
    # Synthesis-only probe. deferred_flatten does a full hierarchical
    # synth-and-map and then re-reads the mapped netlist and runs
    # `synth -flatten` over it a second time; `flatten` maps once, flat.
    # Running both to Yosys.Synthesis and nowhere further is what
    # separates "the TMR fix added 110 flip-flops" from "deferred_flatten
    # costs area on top of that". It is not runnable past step 06:
    # Checker.YosysUnmappedCells aborts on the $paramod module types that
    # `flatten` leaves behind, which is the whole reason the submission
    # carries deferred_flatten.
    flat = list(out) + [
        ("SYNTH_HIERARCHY_MODE", "flatten"),
        (
            "//variant",
            "docs/20 section 3: synthesis-only A/B against the deferred_flatten "
            "baseline. Run with -T Yosys.Synthesis; the flow cannot proceed past "
            "the unmapped-cell checker with this setting.",
        ),
    ]
    # docs/20 open item 1. The submission config carries
    # RUN_KLAYOUT_DRC = 0, so nothing in this repository has ever run the
    # KLayout deck locally -- but the Tiny Tapeout precheck does run it
    # on the submitted GDS, where a failure costs a resubmission round
    # instead of half an hour. One key flipped, everything else identical
    # to the baseline, so a difference in any other sign-off number would
    # itself be the finding.
    drc = list(out) + [
        ("RUN_KLAYOUT_DRC", 1),
        (
            "//variant",
            "docs/20 section 11: run the KLayout DRC deck the Tiny Tapeout "
            "precheck runs, locally, before submission. Identical to "
            "config.json apart from RUN_KLAYOUT_DRC.",
        ),
    ]
    shapes = {}
    for name, (die, deftpl) in SHAPES.items():
        pairs = []
        for k, v in out:
            if k == "DIE_AREA":
                v = die
            elif k == "FP_DEF_TEMPLATE":
                v = "dir::../../../tt/tt/tech/ihp-sg13g2/def/" + deftpl
            pairs.append((k, v))
        pairs.append(("RUN_KLAYOUT_DRC", 1))
        pairs.append(
            (
                "//variant",
                f"docs/23: the pilot at the {name} twelve-tile shape. Exactly two "
                "keys differ from config.json -- DIE_AREA and FP_DEF_TEMPLATE, "
                "both taken from tt/tt/tech/ihp-sg13g2 -- plus RUN_KLAYOUT_DRC, "
                "which is raised to 1 so that one run per shape produces the "
                "whole sign-off set instead of needing the separate "
                "config.klayoutdrc.json pass docs/22 section 2.4 had to make. "
                "Everything else, including CLOCK_PERIOD, PL_TARGET_DENSITY_PCT "
                "and SYNTH_HIERARCHY_MODE, is the submission's own value, so a "
                "difference between the two shapes is attributable to the shape.",
            )
        )
        shapes[name] = pairs
    return base, variant, flat, drc, shapes


def render(pairs):
    return (
        "{\n"
        + ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in pairs)
        + "\n}\n"
    )


def blobs():
    """Record which git blob each source file is, per the docs/18 precedent."""
    files = [
        os.path.join(REPO, "hw", "rtl", n)
        for n in sorted(os.listdir(os.path.join(REPO, "hw", "rtl")))
    ]
    for f in files:
        h = subprocess.run(
            ["git", "hash-object", f], cwd=REPO, capture_output=True, text=True
        ).stdout.strip()
        print(f"  {h}  {os.path.relpath(f, REPO)}")


def main():
    base, variant, flat, drc, shapes = derive()
    targets = {
        os.path.join(HERE, "config.json"): render(base),
        os.path.join(HERE, "config.pnrcorners.json"): render(variant),
        os.path.join(HERE, "config.flatten.json"): render(flat),
        os.path.join(HERE, "config.klayoutdrc.json"): render(drc),
    }
    for name, pairs in shapes.items():
        targets[os.path.join(HERE, f"config.{name}.json")] = render(pairs)
    if "--check" in sys.argv:
        bad = 0
        for path, want in targets.items():
            have = open(path).read() if os.path.exists(path) else ""
            if have != want:
                print(f"DRIFT: {path}")
                bad = 1
        if not bad:
            print("configs match tt/src/config_merged.json")
        return bad
    for path, text in targets.items():
        open(path, "w").write(text)
        print(path)
    print("hw/rtl blobs at generation time:")
    blobs()
    return 0


if __name__ == "__main__":
    sys.exit(main())
