#!/usr/bin/env python3
"""Check -- and, with --apply, insert -- the SPDX header on every source file.

This script is the licence policy of `docs/14-licensing-decision.md`
section 6.4 in machine-readable form. The document says what the licence
set is; this file is what makes the claim true of the tree rather than
asserted about it, which is the same standard `hw/openlane/checker_audit.py`
applies to the flow's own gates.

    python3 scripts/spdx_check.py            report, exit 1 if anything is wrong
    python3 scripts/spdx_check.py --apply    insert the missing headers
    python3 scripts/spdx_check.py --list     print the classification of every file

WHAT IS TAGGED INLINE, AND WHAT IS NOT

A file is tagged inline when it is a SOURCE FILE and its syntax has a
comment. Everything else is covered by path, in `.reuse/dep5` and
`LICENSES.md`, and this script checks that those two agree with the
classification below -- so a file that cannot carry a tag is still
covered by a rule, not by silence.

Four groups are deliberately NOT tagged inline, each for a stated reason:

  tt/**            regenerated by scripts/gen_tt_submission.py from
                   hw/rtl/ and from the upstream Tiny Tapeout template.
                   The Verilog under tt/src/ is byte-identical to
                   hw/rtl/ by `docs/34` section 2.3 and carries its tag
                   from there; the scaffolding stays Apache-2.0 as
                   received. Editing tt/ by hand would break both.
  *.json           has no comment syntax, and six of them are pinned by
                   sha256 inside hw/openlane/pilot_ihp/mkconfig.py
                   (`docs/34` section 5.1). A header would void a freeze.
  *.md *.csv *.tsv documents and measurement data. CC-BY-4.0 by path.
                   The documents are not tagged because `docs/00-index.md`
                   and `sw/tests/test_doc_links.py` parse the first line
                   of every document, and a licence header is not worth
                   a parser change.
  two ISC files    hw/soc/rvformal/insns/insn_div.v and insn_rem.v are
                   corrected copies of riscv-formal's models and carry
                   upstream's ISC notice inline (`docs/14` section 2.1).
                   This script checks they still say ISC.

GENERATED FILES carry the header because their GENERATOR emits it. They
are checked here like any other file; if one fails, re-run its
generator rather than editing it.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COPYRIGHT = "SPDX-FileCopyrightText: 2026 Hasan Melih Akbulut"

HW = "CERN-OHL-W-2.0"   # RTL, testbenches, constraints, formal jobs
SW = "Apache-2.0"       # generators, golden models, harnesses, flow drivers, CI
DOC = "CC-BY-4.0"       # documents and measurement data

# Files that carry a licence that is not this project's to choose.
THIRD_PARTY = {
    "hw/soc/rvformal/insns/insn_div.v": "ISC",
    "hw/soc/rvformal/insns/insn_rem.v": "ISC",
}

# Path prefixes covered by .reuse/dep5 instead of an inline tag.
UNTAGGED_PREFIXES = ("tt/", "LICENSES/", ".reuse/")
UNTAGGED_SUFFIXES = (".json", ".md", ".csv", ".tsv", ".sha256", ".svg",
                     ".gitignore", ".txt", ".ini")
UNTAGGED_NAMES = {"LICENSE", "pytest.ini", ".gitignore"}

# Comment syntax by suffix. The value is (prefix, suffix); a suffix of ""
# means a line comment.
HASH = ("# ", "")
SLASH = ("// ", "")
BLOCK = ("/* ", " */")

SYNTAX = {
    ".v": SLASH, ".vh": SLASH, ".sv": SLASH, ".c": SLASH, ".h": SLASH,
    ".S": SLASH, ".ld": BLOCK,
    ".sdc": HASH, ".sby": HASH, ".tcl": HASH, ".py": HASH, ".sh": HASH,
    ".mk": HASH, ".yml": HASH, ".yaml": HASH, ".awk": HASH, ".cfg": HASH,
    ".ys": HASH,
}

# Hardware sources take CERN-OHL-W-2.0; everything else executable takes
# Apache-2.0. The boundary is `docs/14` section 6.5: tooling is permissive
# so that it can be offered upstream to yosys, LibreLane and IHP-Open-PDK,
# none of which takes reciprocal code.
HW_SUFFIXES = {".v", ".vh", ".sv", ".sdc", ".sby", ".tcl", ".ys"}


def strip_template(name):
    """foo.sdc.in -> .sdc; foo.py -> .py; Makefile.fi -> (Makefile)."""
    if name.startswith("Makefile"):
        return ".mk"
    parts = name.split(".")
    if len(parts) >= 3 and parts[-1] == "in":
        return "." + parts[-2]
    if len(parts) >= 2:
        return "." + parts[-1]
    return ""


def classify(rel):
    """Return (licence, syntax) or (licence, None) for path-covered files."""
    if rel in THIRD_PARTY:
        return THIRD_PARTY[rel], SYNTAX.get(strip_template(Path(rel).name))
    name = Path(rel).name
    if rel.startswith(UNTAGGED_PREFIXES):
        return None, None
    if name in UNTAGGED_NAMES or (rel.endswith(UNTAGGED_SUFFIXES)
                                  and not name.startswith("Makefile")):
        return None, None
    suf = strip_template(name)
    syn = SYNTAX.get(suf)
    if syn is None:
        return None, None
    lic = HW if suf in HW_SUFFIXES else SW
    return lic, syn


def path_licence(rel):
    """The licence a path-covered (untagged) file is under, for LICENSES.md."""
    if rel.startswith("tt/"):
        return "see tt/README.md"
    if rel.endswith((".md", ".csv", ".tsv")):
        return DOC
    if rel.endswith(".json"):
        return HW if rel.startswith(("hw/", "formal/", "tt/")) else SW
    return SW


TAG_RE = re.compile(r"SPDX-License-Identifier:\s*([A-Za-z0-9.\-+ ]+)")


def read_tag(text):
    m = TAG_RE.search(text[:4000])
    return m.group(1).strip() if m else None


def header_lines(lic, syn):
    pre, post = syn
    return [f"{pre}{COPYRIGHT}{post}", f"{pre}SPDX-License-Identifier: {lic}{post}"]


def insert(text, lic, syn):
    lines = text.split("\n")
    at = 0
    # After a shebang, and after a `//` line that a tool requires first.
    if lines and lines[0].startswith("#!"):
        at = 1
    block = header_lines(lic, syn)
    # A blank line after the header, unless the file already starts blank.
    tail = lines[at:]
    if tail and tail[0].strip():
        block = block + [""]
    return "\n".join(lines[:at] + block + tail)


def tracked():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, check=True,
                         capture_output=True, text=True).stdout
    return [l for l in out.split("\n") if l]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    missing, wrong, ok, covered = [], [], 0, 0
    for rel in tracked():
        lic, syn = classify(rel)
        p = ROOT / rel
        if lic is None or syn is None:
            covered += 1
            if args.list:
                print(f"{'path':<18} {path_licence(rel):<18} {rel}")
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            covered += 1
            continue
        have = read_tag(text)
        if args.list:
            print(f"{'inline':<18} {lic:<18} {rel}")
        if have is None:
            if args.apply and rel not in THIRD_PARTY:
                p.write_text(insert(text, lic, syn), encoding="utf-8")
                ok += 1
            else:
                missing.append((rel, lic))
        elif have != lic:
            wrong.append((rel, have, lic))
        else:
            ok += 1

    if args.list:
        return 0

    for rel, lic in missing:
        print(f"MISSING  {lic:<18} {rel}")
    for rel, have, lic in wrong:
        print(f"WRONG    got {have}, expected {lic}: {rel}")
    print(f"\n{ok} tagged, {covered} covered by path, "
          f"{len(missing)} missing, {len(wrong)} wrong")
    return 1 if (missing or wrong) else 0


if __name__ == "__main__":
    sys.exit(main())
